errors...

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -23,7 +23,7 @@ jobs:
 
       - name: Build with Maven
         run: mvn clean package -DskipTests
-        working-directory: ./authuser/authuser  # Ajustando o diretório de trabalho para o comando Maven
+        working-directory: ./authuser/authuser
 
   deploy-staging:
     needs: build
@@ -33,37 +33,30 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Login to Docker Hub
-        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
       - name: Install Docker
-        run: |
-          sudo apt-get update
-          sudo apt-get remove -y docker docker-engine docker.io containerd runc
-          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
-          sudo apt-get update
-          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
-
-      - name: Start Docker service
-        run: |
-          sudo service docker start
-          sudo usermod -aG docker $USER
-          sudo systemctl enable docker
-
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
+        uses: docker/setup-docker@v2
 
       - name: List files in authuser/authuser directory
-        run: ls -l ./authuser/authuser  # Listar os arquivos para verificar a presença do docker-compose.staging.yml
+        run: ls -l ./authuser/authuser
 
       - name: Deploy to Staging
         run: |
           echo "Deploying to Staging Environment"
           docker-compose -f ./docker-compose.staging.yml up -d --build
-        working-directory: ./authuser/authuser  # Define o diretório de trabalho para o comando Docker
+          docker-compose -f ./docker-compose.staging.yml ps
+
+      - name: Check Staging Deployment
+        run: |
+          docker-compose -f ./docker-compose.staging.yml ps
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed!"
+            exit 1
+          fi
 
   deploy-production:
     if: github.ref == 'refs/heads/main'
@@ -74,34 +67,27 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Login to Docker Hub
-        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
       - name: Install Docker
-        run: |
-          sudo apt-get update
-          sudo apt-get remove -y docker docker-engine docker.io containerd runc
-          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-          echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
-          sudo apt-get update
-          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
-
-      - name: Start Docker service
-        run: |
-          sudo service docker start
-          sudo usermod -aG docker $USER
-          sudo systemctl enable docker
-
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
+        uses: docker/setup-docker@v2
 
       - name: List files in authuser/authuser directory
-        run: ls -l ./authuser/authuser  # Listar os arquivos para verificar a presença do docker-compose.production.yml
+        run: ls -l ./authuser/authuser
 
       - name: Deploy to Production
         run: |
           echo "Deploying to Production Environment"
           docker-compose -f ./docker-compose.production.yml up -d --build
-        working-directory: ./authuser/authuser  # Define o diretório de trabalho para o comando Docker
+          docker-compose -f ./docker-compose.production.yml ps
+
+      - name: Check Production Deployment
+        run: |
+          docker-compose -f ./docker-compose.production.yml ps
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed!"
+            exit 1
+          fi
