errors...

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -13,40 +13,34 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
         with:
-          distribution: 'adopt'
-          java-version: '11'
+          distribution: 'temurin'  # 'adopt' foi substituído pelo 'temurin'
+          java-version: '17'
 
       - name: Build with Maven
         run: mvn clean package -DskipTests
+        working-directory: ./authuser/authuser
 
-  deploy-staging:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Deploy to Staging
-        run: |
-          echo "Deploying to Staging Environment"
-          # Comandos para fazer o deploy no ambiente de staging
-          docker-compose -f docker-compose.staging.yml up -d --build
-
-  deploy-production:
-    if: github.ref == 'refs/heads/main'
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
       - name: Deploy to Production
         run: |
           echo "Deploying to Production Environment"
-          # Comandos para fazer o deploy no ambiente de produção
-          docker-compose -f docker-compose.production.yml up -d --build
+          docker-compose -f ./docker-compose.yml up -d --build
+          docker-compose -f ./docker-compose.yml ps
+
+      - name: Check Production Deployment
+        run: |
+          docker-compose -f ./docker-compose.yml ps
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed!"
+            exit 1
+          fi
